name: Create Pull Request to Develop

on:
  push:
    branches-ignore:
      - 'main'
      - 'develop

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: "develop"
          pr_title: "PR from ${{ github.ref_name }}"
          pr_body: "Automatic Pull Request from ${{ github.ref_name }} to `develop`."
          pr_label: "automation"